---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    author: tukov
    name: redis-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: redis-deployment
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-deployment
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
...