---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    author: tukov
    name: worker-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: worker-app-deployment
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-deployment
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
...